"""Record this agent's observed still/pose findings without changing authored assets."""
import hashlib,json,shutil
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
OUT=Path(__file__).resolve().parent/'brief-audit'
OUT.mkdir(exist_ok=False)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
# Findings are manual observations, not a programmatic art score.
notes={
'Ada':('Curved kite shield, quilt/tabard, sun disk, short braid, fitted face and sword fingers are present in source9 close views.', 'Deep finger-web grooves remain visible; fine cuff/guard intersections and shield clearance need close continuous engine review.', 'reports/WC-U440/20260906T153806Z/ada/ada-source9-handoff.json'),
'Mira':('Auburn bun, thick circle focus, coral mantle, satchel clasps/strap and teal details are visible.', 'Hands still read as broad mitten forms and coat panels as relatively rigid slabs at gallery distance; continuous support-hand contact and late Victory staff clearance remain open.', 'reports/WC-U440/20260906T133433Z/six-hero-source-handoff.json'),
'Rowan':('Round glasses, asymmetrical bracket, indigo coat, amber vest and angular collar are visible.', 'The deliberately angular collar remains visually heavy. Two-hand gather, held bracket contact and actual core brightness need continuous engine review; no new hard static failure identified.', 'reports/WC-U440/20260906T133433Z/six-hero-source-handoff.json'),
'Liora':('Pale hair fan, crescent bow, narrow legs and three cloak panels retained. Source8 connects the original sleeve roots into the torso.', 'All seven action curves remain unchanged. Bow draw/string contact and dash landing still need continuous engine review; the observed source7 shoulder gap is repaired in source8.', 'reports/WC-U440/20260906T162705Z-elf-shoulders/liora-candidate8-v2/candidate-result.json'),
'Elin':('Silver crown braid, harp negative space and thick strings, teal tunic and pale sleeve petals are visible.', 'Pale sleeve planes still read as thick rigid petals. Actual broad-chord/basic contrast, hand-string contact and rear clearance need continuous crowded engine review.', 'reports/WC-U440/20260906T133433Z/six-hero-source-handoff.json'),
'Sylas':('Single mantle, asymmetric curved blades, courier lantern/case and repaired source8 sleeve roots are present.', 'The new Attack adds left-blade recovery guard after the original right-hand release. Alternating successive basic cuts required by the brief are not implemented by this single composite cycle; runtime presentation remains necessary. No extra hit or notify was added.', 'reports/WC-U440/20260906T162705Z-elf-shoulders/sylas-candidate8-v2/candidate-result.json'),
'Borin':('Open helmet, two beard braids, low bell hammer with bronze rim and slate armor are visible.', 'No additional hard static defect identified. Heavy hammer grip, beard/shoulder contact and face visibility among stocky neighbors need continuous engine checks.', 'reports/WC-U440/20260906T141605Z/dwarves/HANDOFF.md'),
'Tessa':('Freckles, lifted goggles, mustard coat, horizontal crank crossbow and decorative side wheel are visible.', 'Two-hand support and shot release remain continuous-review obligations; current static face clears the stock. Crossbow width still needs crowd and turn checks.', 'reports/WC-U440/20260906T141605Z/dwarves/HANDOFF.md'),
'Dagna':('Coiled braid, brick coat, square apron and beveled rectangular forge hammer are visible.', 'The current portrait leaves her face clear; prior motion notes about hammer occlusion remain unresolved without continuous review. Pivot/heel lift and two-handed contact need checks.', 'reports/WC-U440/20260906T141605Z/dwarves/HANDOFF.md'),
'Rok':('Topknot, tusks, circular ochre mantle, open off-hand, red sash and broad axe are visible.', 'Current portrait is framed. The retained earlier axe extreme-pose margin case still requires current crowded gameplay checks; rounded hand/axe socket contact needs a closer pass.', 'reports/WC-U440/20260906T141653Z-orcs/orc-source-handoff.json'),
'Zura':('Fork negative space and small sky stone, pale cloud collar, layered blue coat and tusks are visible.', 'Wide cloud-collar slabs and mitten-like staff hand remain fine craft/contact concerns. Staff sweep and crouch coat clearance need continuous review. Current portrait contains the staff tip.', 'reports/WC-U440/20260906T141653Z-orcs/orc-source-handoff.json'),
'Kesh':('Turquoise courier jacket, scarf loop, tan sash, close case and short blades are visible.', 'CONFIRMED current source7 portrait defect: both upper sleeves terminate as exposed flat caps with gaps to the torso. Root authorized a targeted continuous sleeve-root repair after elf handoff. Do not treat this audit snapshot as the later repair result.', 'reports/WC-U440/20260906T141653Z-orcs/orc-source-handoff.json'),
'Cass':('Crimson coat, pale brow streak, single shoulder plate, rigid-backed banner/bracket and long supported blade are visible; source5 eyes fit the head surface.', 'Armor/cloth contact near the single pauldron and two-handed grip remain close-review concerns. Single-hit timing and banner safe area need continuous engine review.', 'reports/WC-U440/20260906T160537Z-cass/cass-source5-handoff.json'),
'Neris':('Cool-brown face, low knot, thick broken-circle headpiece, violet coat, lens and flat chart case are visible; source5 eyes fit the head.', 'CONFIRMED sampled Active presentation gap: lens rises to upper chest, visibly below eye level requested by the brief; both-palms alignment needs a targeted motion review before claiming that requirement complete.', 'reports/WC-U440/20260906T161455Z-face-fit/three-face-source-handoff.json'),
'Orla':('Dark face, silver side braids, rounded hood/apron and thick octagonal lantern are visible; source4 face details fit.', 'Sampled Active opens the free arm and raises the lantern modestly. Lantern handle/hand and knee clearance in Defeat need continuous checks; no additional hard static failure identified.', 'reports/WC-U440/20260906T161455Z-face-fit/three-face-source-handoff.json'),
'Tala':('Moss face, tight braids, arched shoulders, blue sash and rounded road-emblem tower shield are visible; source4 face details fit.', 'Sampled Hit hides most of the face behind the shield near recoil frames4–19. Active holds the mace while extending that arm, so the specified outward free-palm cue is not demonstrated. Neighbor occlusion and planted shield require current engine review.', 'reports/WC-U440/20260906T161455Z-face-fit/three-face-source-handoff.json'),
'Pippa':('Adult freckled face, chestnut curls, green quilt pattern, red scarf, leaf club and orchard buckler are visible in current source7 portrait.', 'Rounded arm/cuff seams require close motion inspection. Her source pilot reports96px game-angle merging of buckler/forearm and foreshortened club; current engine crowded mixed-height comparison remains open.', 'reports/WC-U440/20260906T160405Z/pippa-readback/HANDOFF.md'),
'Finn':('Adult tan face, sandy curls/brim, blue vest, upright bow and distinct hand spacing are visible in source5 portrait.', 'Fitted face is improved. Round sleeve caps are still visually prominent; bowstring/draw-hand contact and careful Active/basic contrast need continuous engine checks.', 'reports/WC-U440/20260906T162841Z/halfling-face-fit/finn-readback/fbx-video-validation.json'),
'Nella':('Rich-brown adult face, solid swept tuft, plum jacket, teal cord and two broad fan batons are visible in source4 portrait.', 'The obsolete projecting hair strands from source3 are absent in this actual source4 portrait. Round sleeve caps/cuff seams and alternating taps/off-hand Active feint need continuous engine review.', 'reports/WC-U440/20260906T163654Z/halfling-final-check/nella'),
'Milo':('Mustached adult face, wavy curls, sky-blue coat, high cream collar and thick spiral wand are visible in source2 portrait.', 'Spiral reads frontally but foreshortened crowd readability remains open. Coat front panels are rather stiff; stir/flick, supported wand contact and umbrella back clearance need continuous engine review.', 'reports/WC-U440/20260906T162841Z/halfling-face-fit/milo-readback/fbx-video-validation.json'),
}
data=json.loads((ROOT/'data/units.json').read_text());rows=[]
for unit in data['units']:
    uid=unit['id'];name=unit['display_name'];source=ROOT/f'art-source/heroes/{uid}/{uid}.blend';manifest=ROOT/f'exports/heroes/{uid}/export_manifest.json'
    row={'id':uid,'display_name':name,'required_art':unit['art'],'brief':'docs/updates/2026-09-auto-chess-inspired/HERO_UPGRADE_BRIEFS.md','source':str(source),'export_manifest':str(manifest)}
    if name in notes:
        m=json.loads(manifest.read_text());assert source.exists() and sha(source)==m['source_sha256'],uid
        portrait=manifest.parent/'Portrait.png';snapshot=OUT/(uid+'-portrait.png');shutil.copy2(portrait,snapshot)
        row.update({'source_revision':m['source_revision'],'geometry_revision':m.get('geometry_source_revision',m.get('geometry_revision')),'animation_revision':m['animation_revision'],'source_sha256':sha(source),'manifest_sha256':sha(manifest),'source_export_hash_parity':True,'portrait_snapshot':str(snapshot),'portrait_sha256':sha(snapshot),'observed':notes[name][0],'outstanding':notes[name][1],'supporting_evidence':notes[name][2],'status':'ACTUAL_STILL_REVIEW_WITH_OPEN_ACCEPTANCE'})
    else:
        row.update({'status':'PENDING_DRAGONKIN_PRODUCTION_AT_THIS_AUDIT','observed':'Individual dossier and upgrade brief reviewed; no source or portrait inspection claimed.','outstanding':'Required true Dragonkin muzzle/neck/horns, individual costume/gear and all7 clips remain pending production at this snapshot.','source_exists_at_snapshot':source.exists(),'manifest_exists_at_snapshot':manifest.exists()})
    rows.append(row)
record={'status':'READ_ONLY_24_BRIEF_AND_20_CURRENT_PORTRAIT_AUDIT','utc':datetime.now(timezone.utc).isoformat(),'units_source_sha256':sha(ROOT/'data/units.json'),'method':'Manual view of actual current portraits for20heroes, plus this lane actual source close views and sampled seven-clip sheets. Canonical full art fields are embedded verbatim for traceability; program output is not an art assessment.','heroes':rows,'common_open_gates':['Continuous normal-speed review of all168 hero/clip combinations in Unreal','Both team orientations at1080p/720p and96px crowded mixed-height identification','Fine grip, joint, cloth/prop contact and LOD transition review in actual gameplay','Release-synchronized individual VFX/audio and actual effective outcome review','Finished-model visual approval; no numerical metadata or supplied motion file alone proves it'],'scope':'Read-only source/dossier audit. Does not verify gameplay, package, human play, LAN, performance or skill implementation.'}
(OUT/'24-hero-brief-audit.json').write_text(json.dumps(record,indent=2)+'\n')
lines=['# 24-hero source and brief audit','',f"Actual audit UTC: {record['utc']}",'','All24 individual upgrade briefs and canonical art fields were reviewed. Current portraits for20 authored heroes were inspected; four Dragonkin are pending in this snapshot. This is a read-only art review, not finished-art or packaged-play acceptance. Frozen portrait copies and exact source/manifest hashes are in the companion JSON.','', '| Hero | Source / geometry / animation | Observed implementation | Outstanding finding |','|---|---|---|---|']
for row in rows:
    rev=' / '.join(str(row[x]) for x in ['source_revision','geometry_revision','animation_revision']) if 'source_revision' in row else 'Pending'
    lines.append(f"| {row['display_name']} | {rev} | {row['observed']} | {row['outstanding']} |")
lines+=['','## Cross-roster acceptance still open','']+['- '+x for x in record['common_open_gates']]+['','## Concrete priority findings','','1. Repair the confirmed current Kesh7 sleeve-to-torso gaps using the authorized targeted source revision.','2. Finish actual review of repaired Liora8/Sylas8. Sylas left recovery guard is not alternating successive attacks.','3. Review Neris lens-to-eye Active staging and Tala shield recoil/free-hand cue against their explicit briefs before calling those presentation requirements delivered.','4. Continue individual fine hand/face/cloth craft and continuous motion inspection. The flat/faceted tabletop style is retained, but rough joint or grip construction is not accepted solely because the mesh exports.','','The audit does not change canonical rules, timing, source assets or ownership. Source revisions may advance after this snapshot; consult hashes rather than treating this as the latest release matrix.','']
(OUT/'24-hero-brief-audit.md').write_text('\n'.join(lines));print(json.dumps({'report':str(OUT),'heroes':len(rows),'portraits':sum('portrait_snapshot' in r for r in rows)},indent=2))
