import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];OUT=Path(__file__).resolve().parent
rows=[]
for name,uid in [('liora','wc_u_elf_ranger'),('sylas','wc_u_elf_rogue')]:
    source=ROOT/f'art-source/heroes/{uid}/{uid}.blend';folder=ROOT/f'exports/heroes/{uid}';m=json.loads((folder/'export_manifest.json').read_text());check=json.loads((OUT/f'{name}-verified8/published-verification.json').read_text());seq=json.loads((OUT/f'{name}-verified8/normal-speed-evidence.json').read_text());before=json.loads((OUT/f'{name}-candidate8-v2/before-export-manifest.json').read_text())
    assert hashlib.sha256(source.read_bytes()).hexdigest()==check['source_sha256']==m['source_sha256']
    assert len(seq['clips'])==7 and len(check['mesh_fbx_readbacks'])==3
    retained=[clip for clip in m['clips'] if before['files'][f'AN_{uid}_{clip}.fbx']==m['files'][f'AN_{uid}_{clip}.fbx']]
    assert len(retained)==(7 if name=='liora' else 6)
    rows.append({'name':name.title(),'unit_id':uid,'source':str(source),'exports':str(folder),'source_revision':m['source_revision'],'geometry_revision':m['geometry_source_revision'],'animation_revision':m['animation_revision'],'source_sha256':m['source_sha256'],'manifest_sha256':hashlib.sha256((folder/'export_manifest.json').read_bytes()).hexdigest(),'LOD_triangles':[m['triangles']]+[r['triangles'] for r in m['lods']],'retained_animation_FBX_hashes':retained,'saved_source_mesh_skin_and_motion':check,'encoded_source_review_frames':sum(c['frames'] for c in seq['clips']),'encoded_source_review_duration_ms':sum(c['duration_ms'] for c in seq['clips']),'actual_reviewed_views':['front','side','back','three-quarter'],'actual_reviewed_source_contact_sheets':[c['clip'] for c in seq['clips']],'arm_review':str(OUT/f'{name}-candidate8-v2/arm-review-v2/candidate-deformation-review.json')})
record={'status':'TWO_ELF_SOURCE8_FROZEN_EXPORT_VERIFIED_SAMPLED_VISUAL_REVIEW','heroes':rows,'change':'Extend the existing sleeve top rings inward and blend to spine_03 so torso and upper arm connect; preserve all sleeve geometry beyond the first two rings and all gear/hair/palette/rest skeleton. No new floating caps.','Sylas_Attack_change':'Only left upperarm/lowerarm recovery guard changed. Right-blade release remains frame16 with one hit; other6 clips exact unchanged. Successive alternating attacks remain a runtime presentation requirement.','actual_animation_FBX_readback':json.loads((OUT/'sylas-Attack-readback.json').read_text()),'review_findings':['Connected shoulder and elbow silhouettes in all14 sampled final clip sheets and70 candidate poses; no sampled explosive deformation observed.','Existing broad mitten hands, cuff/guard contacts and fine cloth intersections remain close continuous-review concerns.','Liora bow draw/release and both dash/foot landing clips still require continuous engine evaluation.','No finished-art, continuous playback, Unreal-import, packaged or combat acceptance asserted by this source handoff.'],'retained_failures':['Initial candidate8 selection looked only in BODY, failed expected sleeve component count before saving/publishing; candidate8-v2 explicitly includes COSTUME.','First quick arm-review relative render path wrote70 actual PNGs under C:/reports rather than the workspace; fresh absolute-path arm-review-v2 rerendered all70 within workspace.'],'orphan_cleanup_blocker':{'tool':'tools.exec_command','action':'PowerShell Move-Item of the two misplaced arm-review directories into the workspace and removal of then-empty C:/reports/WC-U440 ancestors','automatic_approval_review_result':'Rejected before execution: blocked by policy','no_retry_or_bypass':True,'paths':['C:/reports/WC-U440/20260906T162705Z-elf-shoulders/liora-candidate8-v2/arm-review','C:/reports/WC-U440/20260906T162705Z-elf-shoulders/sylas-candidate8-v2/arm-review'],'status':'70 supplemental orphan PNGs preserved; not current acceptance; no cleanup completed'},'next':'Root-owned Unreal reimport/cold7clip review for each frozen source; continue authorized Kesh shoulder repair separately.'}
(OUT/'elf-source8-handoff.json').write_text(json.dumps(record,indent=2)+'\n')
lines=['# Liora8 and Sylas8 source/export handoff','','Both sources and exports are frozen. The existing continuous sleeve roots now extend into the torso with spine/upper-arm blending. This is an incremental repair to observed detached shoulders; costume, hair, gear, palette and the rest skeleton remain intact.','','| Hero | Source / geometry / animation | LOD triangles | Retained animation FBXs |','|---|---|---|---|']
for r in rows:lines.append(f"| {r['name']} | {r['source_revision']} / {r['geometry_revision']} / {r['animation_revision']} | {' / '.join(map(str,r['LOD_triangles']))} | {len(r['retained_animation_FBX_hashes'])} /7 |")
lines+=['','Each saved source passed skin/structural/all7 motion invariants,14 export hashes and3 actual independent mesh-FBX readbacks. Sylas Attack also passed a fresh actual animation-FBX import:40 frames at60fps,27 bones, finite poses and an animated left recovery guard. No animation timing or damage event was added.','', 'For both heroes I inspected actual front/side/back/three-quarter renders,35 candidate deformation poses, and all7 final Cycles contact sheets. All14 source movies were encoded at20fps/1x with frame/duration readback. Those sampled frames and valid movies do not certify continuous visual approval.','']
for r in rows:lines+= [f"## {r['name']}",'',f"Source: `{r['source']}`",f"Source SHA256: `{r['source_sha256']}`",f"Manifest SHA256: `{r['manifest_sha256']}`",f"Review: `{OUT/(r['name'].lower()+'-verified8')}`",f"Actual encoded source samples: {r['encoded_source_review_frames']} frames / {r['encoded_source_review_duration_ms']}ms across7 clips.",'']
lines+=['## Remaining limits','','Sylas has a right strike followed by an off-hand recovery guard in one composite Attack cycle. The brief asks for alternating successive cuts; that runtime presentation remains open. Fine grip/cuff contact, cloth/gear intersections, bow draw, dash landing and crowded board readability remain continuous Unreal review obligations. No hero is labelled finished from this handoff.','','## Retained failures and cleanup blocker','','The first candidate selection failed before publication and is retained. The initial quick arm-review renderer wrote70 PNGs outside the workspace because its output path was relative. Both reviews were rerun successfully to fresh, resolved absolute paths under `arm-review-v2`; those are the current arm evidence.','','Automatic approval review rejected the `tools.exec_command` PowerShell move/empty-directory cleanup action with **“blocked by policy”**, before execution. No retry or bypass was attempted. The two `C:/reports/WC-U440/20260906T162705Z-elf-shoulders/<liora-candidate8-v2|sylas-candidate8-v2>/arm-review` directories remain supplemental orphan evidence. Their exact paths and the denied action are recorded in the JSON.','','Root may reimport the frozen exports now. The independent24 brief/20 portrait audit is in `brief-audit/24-hero-brief-audit.md`.','']
(OUT/'elf-source8-handoff.md').write_text('\n'.join(lines));print(json.dumps({'status':record['status'],'source_hashes':{r['name']:r['source_sha256'] for r in rows}},indent=2))
