import bpy,json,hashlib
from pathlib import Path
R=Path('C:/Users/iputu/Documents/Wonder Chess/art-source/asset-studio/wc_u_human_guardian/stages/body-costume/BW5/armor');source=R/'ada_bw5_armor_checkpoint_r003_ART_REVISE.blend';sha=hashlib.sha256(source.read_bytes()).hexdigest();frames=R/'motion/r003/frames';frames.mkdir(parents=True,exist_ok=True)
s=bpy.data.scenes['BW4_ARMOR_LOCAL_AUTHORING_ONLY'];bpy.context.window.scene=s;s.frame_start=1;s.frame_end=97;s.frame_step=1;s.render.fps=24;s.render.engine='BLENDER_WORKBENCH'
s.camera=bpy.data.objects['BW4_Camera_three_quarter'];shade=s.display.shading;shade.light='STUDIO';shade.color_type='SINGLE';shade.single_color=(.55,.55,.55);shade.show_shadows=True;shade.show_cavity=True;shade.cavity_type='BOTH';shade.background_type='WORLD';s.world.color=(.09,.09,.09)
s.render.resolution_x=800;s.render.resolution_y=800;s.render.resolution_percentage=100;s.render.image_settings.media_type='IMAGE';s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGB';s.render.filepath=str(frames/'frame_');s.render.film_transparent=False;s.use_nodes=False;s.render.use_sequencer=False;s.view_settings.view_transform='Standard';s.view_settings.look='None'
bpy.ops.render.render(animation=True,scene=s.name)
files=[frames/f'frame_{f:04}.png' for f in range(1,98)];assert all(p.exists() for p in files)
video=bpy.data.scenes.new('BW4_TEMP_ARMOR_VIDEO');bpy.context.window.scene=video;video.frame_start=1;video.frame_end=97;video.render.resolution_x=800;video.render.resolution_y=800;video.render.resolution_percentage=100;video.render.fps=24;video.render.image_settings.media_type='VIDEO';video.render.image_settings.file_format='FFMPEG';video.render.ffmpeg.format='MPEG4';video.render.ffmpeg.codec='H264';video.render.ffmpeg.constant_rate_factor='MEDIUM';video.render.ffmpeg.audio_codec='NONE';movie=R/'motion/r003/BW5_ARMOR_AUTHORING_DIAGNOSTIC_NOT_GAME_CLIPS.mp4';video.render.filepath=str(movie);video.view_settings.view_transform='Standard';video.view_settings.look='None';ed=video.sequence_editor_create();strip=ed.strips.new_image('Actual source rendered frames',str(files[0]),channel=1,frame_start=1)
for p in files[1:]:strip.elements.append(p.name)
label=ed.strips.new_effect('Scope',type='TEXT',channel=2,frame_start=1,length=97);label.text='BW5 TORSO / ART_REVISE\nCOLLAR / SHOULDERS ARE BW4 CONTEXT - NOT GAME CLIPS';label.font_size=22;label.location=(.5,.94);label.color=(1,1,1,1);label.use_shadow=True;video.render.use_sequencer=True
bpy.ops.render.render(animation=True,scene=video.name)
assert hashlib.sha256(source.read_bytes()).hexdigest()==sha
(R/'motion/r003/source_record.json').write_text(json.dumps({'source':str(source),'sha256':sha,'movie':str(movie),'movie_sha256':hashlib.sha256(movie.read_bytes()).hexdigest(),'frames':97,'fps':24,'resolution':[800,800],'action':bpy.data.objects['BW4_Armor_Independent_Rig'].animation_data.action.name,'pose_labels':json.loads(s['pose_labels']),'camera':s.camera.name,'camera_matrix_world':list(map(list,s.camera.matrix_world)),'renderer':'BLENDER_WORKBENCH','scope':'Native full integer-frame authoring diagnostic, not actual seven runtime clips. Fixed same camera. Head/cuff/other parts unresolved. No source save.'},indent=2))
print('MOTION_COMPLETE')
