import hashlib,json
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path('C:/Users/iputu/Documents/Wonder Chess');OUT=Path(__file__).parent;UID='wc_u_human_guardian'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
source=ROOT/f'art-source/heroes/{UID}/{UID}.blend';exports=ROOT/f'exports/heroes/{UID}';candidate=OUT/'candidate9-v8';verified=OUT/'verified9'
old=json.loads((candidate/'before-export-manifest.json').read_text());m=json.loads((exports/'export_manifest.json').read_text());checks=json.loads((verified/'published-verification.json').read_text());encoded=json.loads((verified/'normal-speed-evidence.json').read_text());details=json.loads((candidate/'candidate-result.json').read_text())
assert m['source_revision']==9 and sha(source)==m['source_sha256']==checks['source_sha256']
assert sha(exports/'export_manifest.json')==checks['manifest_sha256']
assert all(sha(exports/f)==d for f,d in m['files'].items())
assert all(m['files'][f'AN_{UID}_{clip}.fbx']==old['files'][f'AN_{UID}_{clip}.fbx'] for clip in m['clips'])
assert len(encoded['clips'])==7
report={'timestamp_utc':datetime.now(timezone.utc).isoformat(),'status':'SOURCE9_EXPORTED_AND_SAMPLED_SOURCE_REVIEWED_UNREAL_REIMPORT_PENDING','source':str(source),'source_sha256':sha(source),'manifest':str(exports/'export_manifest.json'),'manifest_sha256':sha(exports/'export_manifest.json'),'source_revision':9,'geometry_revision':8,'animation_revision':8,'triangles':[x['triangles'] for x in checks['mesh_fbx_readbacks']],'source_before_sha256':old['source_sha256'],'preserved_invariants':details['preserved_invariants'],'unchanged_animation_fbx_count':7,'file_hashes_verified':len(m['files']),'independent_mesh_fbx_readbacks':3,'source_clip_numeric_checks':7,'source_clip_contact_sheets_inspected':list(m['clips']),'continuous_playback_review':False,'Unreal_reimport_verified_in_this_lane':False,'final_art_accepted':False,'before_views':str(OUT/'inspection8'),'after_views':str(candidate),'source_and_export_evidence':str(verified/'published-verification.json'),'normal_speed_media_evidence':str(verified/'normal-speed-evidence.json'),'changes':details['changes'],'preserved':details['not_changed'],'open_reviews':['Current Unreal revision/reimport and texture consistency','Continuous all-seven playback at gallery and gameplay camera','Grip/cuff/guard intersections at release and terminal poses','Face and surface artistic acceptance; candidate is not certified finished art','Performance comparison on named hardware at game camera'],'retained_failures':['candidate9-v1: Blender UV collection clear() API failure; source8 preserved','candidate9-v2: UV name mismatch made remeshed hands use incorrect swatch; actual renders retained','candidate9-v3: close facial view showed eye/head crossing; tessellated surface-fit repaired it','candidate9-v5: structural preflight failed at 26338 triangles; narrowed hand reduction, not increased budget','Earlier candidate close views exposed rough finger/palm joins; curl roots extended into fused palm']}
assert not (OUT/'ada-source9-handoff.json').exists()
(OUT/'ada-source9-handoff.json').write_text(json.dumps(report,indent=2)+'\n')
text=['# Ada source9 gallery polish handoff','',f"Ada is frozen at source9 / geometry8 / animation8 with {' / '.join(map(str,report['triangles']))} LOD triangles. The existing head shell, braid, coat, armor, shield and sword are preserved; all seven source action curves and animation FBX hashes remain unchanged.",'','Changes are limited to fitted shallow eye/iris/brow geometry, a tapered nose and restrained lip contour, and existing palms fused into modeled finger/thumb grips. No shared rig, material, canonical data or Unreal binary was edited.','',f"[Saved source](<{source}>) · [Export manifest](<{exports/'export_manifest.json'}>) · [Before close face](<{OUT/'inspection8/face.png'}>) · [After close face](<{candidate/'face.png'}>) · [Before grip](<{OUT/'inspection8/sword-grip.png'}>) · [After grip](<{candidate/'sword-grip.png'}>)",'',f"Source SHA-256: `{report['source_sha256']}`",'',f"Manifest SHA-256: `{report['manifest_sha256']}`",'','Verification passed for 14 file hashes, saved-source skin/root/scale/support checks across seven clips, and three independent mesh-FBX readbacks. Actual Blender frames were encoded at 20 Hz / 1x and all seven final sampled contact sheets were inspected. This does not certify continuous playback, in-engine rendering, animation-FBX import or finished art.','','The short lip line and faceted nose remain deliberate stylization. Fingers retain clear grooves at close zoom; actual cuff/guard contacts and combat-camera readability remain integration review concerns. The existing armor/cloth silhouette was retained because this inspection did not justify wholesale replacement.','','Retained failed attempts:','']+['- '+s for s in report['retained_failures']]+['','Required integration checks:','']+['- '+s for s in report['open_reviews']]
(OUT/'ada-source9-handoff.md').write_text('\n'.join(text)+'\n');print(json.dumps({'status':report['status'],'files':14,'clips':7,'mesh_readbacks':3,'triangles':report['triangles'],'source_sha256':report['source_sha256'],'manifest_sha256':report['manifest_sha256']}))
