"""Write the Cass revision5 handoff after actual sampled-image review is complete."""
import hashlib,json
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path('C:/Users/iputu/Documents/Wonder Chess');OUT=Path(__file__).parent;UID='wc_u_human_warrior'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
source=ROOT/f'art-source/heroes/{UID}/{UID}.blend';exports=ROOT/f'exports/heroes/{UID}';candidate=OUT/'candidate5-v2';verified=OUT/'verified5'
old=json.loads((candidate/'before-export-manifest.json').read_text());m=json.loads((exports/'export_manifest.json').read_text());checks=json.loads((verified/'published-verification.json').read_text());encoded=json.loads((verified/'normal-speed-evidence.json').read_text());detail=json.loads((candidate/'candidate-result.json').read_text());preserved=json.loads((OUT/'preserved-geometry.json').read_text())
assert m['source_revision']==5 and sha(source)==m['source_sha256']==checks['source_sha256']
assert sha(exports/'export_manifest.json')==checks['manifest_sha256']
assert all(sha(exports/f)==digest for f,digest in m['files'].items())
unchanged=[f for f in m['files'] if old['files'].get(f)==m['files'][f]]
assert all(f'AN_{UID}_{clip}.fbx' in unchanged for clip in m['clips'])
assert len(encoded['clips'])==7 and preserved['status']=='PASS'
report={'timestamp_utc':datetime.now(timezone.utc).isoformat(),'status':'SOURCE5_EXPORTED_AND_SAMPLED_SOURCE_REVIEWED_UNREAL_ACCEPTANCE_SEPARATE','source':str(source),'source_sha256':sha(source),'manifest':str(exports/'export_manifest.json'),'manifest_sha256':sha(exports/'export_manifest.json'),'source_revision':5,'geometry_revision':5,'animation_revision':1,'triangles':[x['triangles'] for x in checks['mesh_fbx_readbacks']],'source_before_sha256':old['source_sha256'],'preserved_invariants':detail['preserved_invariants'],'unchanged_export_files':unchanged,'preserved_geometry_audit':str(OUT/'preserved-geometry.json'),'file_hashes_verified':len(m['files']),'independent_mesh_fbx_readbacks':3,'source_clip_numeric_checks':7,'source_clip_contact_sheets_inspected':list(m['clips']),'continuous_playback_review':False,'Unreal_reimport_verified_in_this_lane':False,'final_art_accepted':False,'before_views':str(OUT),'after_views':str(candidate),'source_and_export_evidence':str(verified/'published-verification.json'),'normal_speed_media_evidence':str(verified/'normal-speed-evidence.json'),'changes':['Old floating eye boxes replaced by shallow curved rings fitted to the actual head surface','Dark pupil and white highlight remain separate readable layers over the original brown iris palette','Brows reconstructed as sampled surface strips with the original expression and pale brow streak'],'preserved':detail['preserved'],'open_reviews':['Actual Unreal surface, portrait and LOD transition inspection','Continuous all-seven playback at gallery and game camera','Previously authored costume contacts and two-handed blade support','Fine face, hand and anatomy artistic acceptance remains separate','Named-hardware runtime cost'],'retained_failures':['candidate5-v1: original brow vertex projection broke sparse surfaces against the curved forehead, and a palette misunderstanding made pupils too small; six actual failed-candidate renders retained, source4 unchanged','A source inspection helper assumed a dimensions key absent from the existing component utility; its failed log is retained separately in the next-three facial inspection task']}
assert not (OUT/'cass-source5-handoff.json').exists()
(OUT/'cass-source5-handoff.json').write_text(json.dumps(report,indent=2)+'\n')
lines=['# Cass source5 targeted facial handoff','',f"Cass is frozen at source5 / geometry5 / animation1 with {' / '.join(map(str,report['triangles']))} LOD triangles. This revision fits the eyes and brows to the existing head. It preserves the head shell, nose, lips, ears, hair, pale brow identity, complete costume and equipment.",'','The fresh saved-source audit confirms that every retained vertex coordinate, palette swatch and bone weight outside the intentionally replaced facial layers has the same canonical signature as source4. All seven action curves, rest skeleton and seven animation FBX hashes are unchanged.','',f"[Source](<{source}>) · [Export manifest](<{exports/'export_manifest.json'}>) · [Before face](<{OUT/'before-face.png'}>) · [After face](<{candidate/'face.png'}>) · [After three-quarter face](<{candidate/'face-three-quarter.png'}>)",'',f"Source SHA-256: `{report['source_sha256']}`",'',f"Manifest SHA-256: `{report['manifest_sha256']}`",'','Fourteen exported file hashes, seven saved-source motion/skin checks and three independent normalized mesh-FBX readbacks passed. All seven actual 20 Hz source contact sheets were inspected and encoded as 1x review GIFs. This is sampled source review, not continuous playback or finished-art approval.','','The retained layered cloth and armor are outside this facial revision; side-view pauldron/clothing contact and precise two-handed sword contact remain integration/art review concerns. No canonical data, shared rig/material or Unreal binary was changed.','','Retained attempt: candidate5-v1 exposed sparse brow/head intersections and an incorrect tiny-pupil treatment. Candidate5-v2 replaced those surfaces with denser fitted strips and preserved the intended brown iris / dark pupil / white glint layers.','','Required next checks:','']+['- '+s for s in report['open_reviews']]
(OUT/'cass-source5-handoff.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'status':report['status'],'triangles':report['triangles'],'source_sha256':report['source_sha256'],'manifest_sha256':report['manifest_sha256']}))
