#pragma once
#include "Simulation/WonderSimulation.h"
inline wc::Catalog FixtureCatalog() { wc::Catalog c;
c.schemaVersion = "3.1.0";
c.balanceVersion = "alpha_24_v0.4.1";
c.contentDigest = "5ba20f6687bcd100616cd095c9741f1ad29bbb19b22c47204c0526adb8f3931a";
c.rules.columns = 8;
c.rules.rows = 8;
c.rules.deploymentRows = 4;
c.rules.tileSizeCm = 200;
c.rules.tickMs = 50;
c.rules.minAttackRate = 250;
c.rules.maxAttackRate = 2500;
c.rules.maxHealth = 100000000;
c.rules.maxArmor = 10000;
c.rules.maxRawDamage = 10000000;
c.rules.starMultiplierBp = {10000,18000,32400};
c.rules.seatCount = 8;
c.rules.startingHealth = 60;
c.rules.maxRounds = 40;
c.rules.firstPreparationMs = 45000;
c.rules.preparationMs = 25000;
c.rules.combatTimeoutMs = 40000;
c.rules.settlementMs = 4000;
c.rules.drawDamage = 2;
c.rules.neutralOpeningRounds = 3;
c.rules.neutralEvery = 5;
c.rules.neutralOpeningDamage = 0;
c.rules.neutralLossDamage = 2;
c.rules.lossStages.push_back({1,6,2});
c.rules.lossStages.push_back({7,12,4});
c.rules.lossStages.push_back({13,40,6});
c.rules.startingGold = 10;
c.rules.benchCapacity = 8;
c.rules.shopSlots = 5;
c.rules.rerollCost = 2;
c.rules.baseIncome = 5;
c.rules.winIncome = 1;
c.rules.neutralWinIncome = 2;
c.rules.interestDivisor = 10;
c.rules.interestCap = 3;
c.rules.startingLevel = 3;
c.rules.maximumLevel = 6;
c.rules.buyXpGold = 4;
c.rules.buyXpAmount = 4;
c.rules.passiveXp = 2;
c.rules.xpToNext[3] = 4;
c.rules.xpToNext[4] = 8;
c.rules.xpToNext[5] = 12;
c.rules.shopWeights[3] = {7500,2500,0};
c.rules.shopWeights[4] = {5500,4000,500};
c.rules.shopWeights[5] = {3500,5000,1500};
c.rules.shopWeights[6] = {2000,5000,3000};
c.rules.botObservationMs = 1500;
c.rules.botRepositionCutoffMs = 3000;
{ wc::UnitDef u;
u.id = "wc_u_human_guardian";
u.name = "Ada Brightshield";
u.displayName = "Ada";
u.race = "human";
u.unitClass = "guardian";
u.cost = 1;
u.roleTags.push_back("tank");
u.health = 105000;
u.attackDamage = 4800;
u.attackRate = 700;
u.range = 1;
u.armor = 35;
u.resistance = 15;
u.movementRate = 1000;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_human_guardian";
u.ability.name = "Sun Guard";
u.ability.firstCastMs = 2000;
u.ability.cooldownMs = 8000;
u.ability.castMs = 300;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 0;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::Self;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Shield;
e.durationMs = 3000;
e.magnitude = {20000,36000,64800};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_human_priest";
u.name = "Mira Dawnwell";
u.displayName = "Mira";
u.race = "human";
u.unitClass = "priest";
u.cost = 1;
u.roleTags.push_back("healer");
u.health = 65000;
u.attackDamage = 3400;
u.attackRate = 750;
u.range = 3;
u.armor = 10;
u.resistance = 20;
u.movementRate = 1050;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_human_priest";
u.ability.name = "Mend";
u.ability.firstCastMs = 3000;
u.ability.cooldownMs = 7000;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 8;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::LowestHealthAlly;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Heal;
e.durationMs = 0;
e.magnitude = {18000,32400,58300};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_human_mage";
u.name = "Rowan Emberwick";
u.displayName = "Rowan";
u.race = "human";
u.unitClass = "mage";
u.cost = 2;
u.roleTags.push_back("caster");
u.health = 62000;
u.attackDamage = 4500;
u.attackRate = 700;
u.range = 3;
u.armor = 8;
u.resistance = 20;
u.movementRate = 1000;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_human_mage";
u.ability.name = "Ember Burst";
u.ability.firstCastMs = 3500;
u.ability.cooldownMs = 8000;
u.ability.castMs = 450;
u.ability.recoveryMs = 300;
u.ability.travelMs = 250;
u.ability.radius = 1;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemyArea;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Magic;
e.durationMs = 0;
e.magnitude = {15000,27000,48600};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_elf_ranger";
u.name = "Liora Leafstep";
u.displayName = "Liora";
u.race = "elf";
u.unitClass = "ranger";
u.cost = 1;
u.roleTags.push_back("ranged");
u.health = 67000;
u.attackDamage = 6000;
u.attackRate = 850;
u.range = 4;
u.armor = 10;
u.resistance = 10;
u.movementRate = 1150;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_elf_ranger";
u.ability.name = "Leafstep";
u.ability.firstCastMs = 2000;
u.ability.cooldownMs = 7500;
u.ability.castMs = 200;
u.ability.recoveryMs = 150;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 2;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::RetreatFromCurrentEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Dash;
e.durationMs = 0;
e.magnitude = {0,0,0};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_elf_priest";
u.name = "Elin Moonsong";
u.displayName = "Elin";
u.race = "elf";
u.unitClass = "priest";
u.cost = 2;
u.roleTags.push_back("support");
u.health = 70000;
u.attackDamage = 3500;
u.attackRate = 800;
u.range = 3;
u.armor = 10;
u.resistance = 25;
u.movementRate = 1050;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_elf_priest";
u.ability.name = "Quick Song";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 9000;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 1;
u.ability.range = 1;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::AdjacentAllies;
{ wc::AbilityEffect e;
e.effect = wc::Effect::StatModifier;
e.durationMs = 3000;
e.magnitude = {2000,2500,3000};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_elf_rogue";
u.name = "Sylas Duskrun";
u.displayName = "Sylas";
u.race = "elf";
u.unitClass = "rogue";
u.cost = 3;
u.roleTags.push_back("control");
u.health = 79000;
u.attackDamage = 7400;
u.attackRate = 1050;
u.range = 1;
u.armor = 18;
u.resistance = 12;
u.movementRate = 1250;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_elf_rogue";
u.ability.name = "Backline Leap";
u.ability.firstCastMs = 1000;
u.ability.cooldownMs = 8500;
u.ability.castMs = 200;
u.ability.recoveryMs = 150;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 8;
u.ability.maxTargets = 12;
u.ability.maxDash = 7;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::FarthestEnemyAdjacent;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Dash;
e.durationMs = 0;
e.magnitude = {0,0,0};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_dwarf_guardian";
u.name = "Borin Stonebell";
u.displayName = "Borin";
u.race = "dwarf";
u.unitClass = "guardian";
u.cost = 1;
u.roleTags.push_back("tank");
u.health = 110000;
u.attackDamage = 4400;
u.attackRate = 650;
u.range = 1;
u.armor = 40;
u.resistance = 10;
u.movementRate = 900;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_dwarf_guardian";
u.ability.name = "Bell Stomp";
u.ability.firstCastMs = 3000;
u.ability.cooldownMs = 8500;
u.ability.castMs = 400;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 1;
u.ability.range = 1;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::AdjacentEnemies;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Stun;
e.durationMs = 1000;
e.magnitude = {0,0,0};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_dwarf_ranger";
u.name = "Tessa Brassbolt";
u.displayName = "Tessa";
u.race = "dwarf";
u.unitClass = "ranger";
u.cost = 2;
u.roleTags.push_back("ranged");
u.health = 76000;
u.attackDamage = 6800;
u.attackRate = 800;
u.range = 4;
u.armor = 20;
u.resistance = 10;
u.movementRate = 950;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_dwarf_ranger";
u.ability.name = "Heavy Bolt";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 6500;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 150;
u.ability.radius = 0;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Physical;
e.durationMs = 0;
e.magnitude = {17000,30600,55100};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_dwarf_warrior";
u.name = "Dagna Anvilheart";
u.displayName = "Dagna";
u.race = "dwarf";
u.unitClass = "warrior";
u.cost = 2;
u.roleTags.push_back("melee");
u.health = 100000;
u.attackDamage = 7000;
u.attackRate = 800;
u.range = 1;
u.armor = 25;
u.resistance = 15;
u.movementRate = 1000;
u.attackWindupMs = 350;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_dwarf_warrior";
u.ability.name = "Hammer Sweep";
u.ability.firstCastMs = 3500;
u.ability.cooldownMs = 8000;
u.ability.castMs = 400;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 1;
u.ability.range = 1;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::AdjacentEnemies;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Physical;
e.durationMs = 0;
e.magnitude = {14000,25200,45400};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_orc_warrior";
u.name = "Rok Sunward";
u.displayName = "Rok";
u.race = "orc";
u.unitClass = "warrior";
u.cost = 1;
u.roleTags.push_back("melee");
u.health = 95000;
u.attackDamage = 6400;
u.attackRate = 850;
u.range = 1;
u.armor = 20;
u.resistance = 15;
u.movementRate = 1100;
u.attackWindupMs = 350;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_orc_warrior";
u.ability.name = "Battle Rhythm";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 8500;
u.ability.castMs = 250;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 0;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::Self;
{ wc::AbilityEffect e;
e.effect = wc::Effect::StatModifier;
e.durationMs = 3000;
e.magnitude = {3000,3500,4000};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_orc_mage";
u.name = "Zura Stormcall";
u.displayName = "Zura";
u.race = "orc";
u.unitClass = "mage";
u.cost = 3;
u.roleTags.push_back("caster");
u.health = 75000;
u.attackDamage = 5000;
u.attackRate = 750;
u.range = 3;
u.armor = 12;
u.resistance = 25;
u.movementRate = 1000;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_orc_mage";
u.ability.name = "Storm Ring";
u.ability.firstCastMs = 4000;
u.ability.cooldownMs = 10000;
u.ability.castMs = 600;
u.ability.recoveryMs = 300;
u.ability.travelMs = 300;
u.ability.radius = 2;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemyArea;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Magic;
e.durationMs = 0;
e.magnitude = {19000,34200,61600};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_orc_rogue";
u.name = "Kesh Quickwind";
u.displayName = "Kesh";
u.race = "orc";
u.unitClass = "rogue";
u.cost = 2;
u.roleTags.push_back("control");
u.health = 82000;
u.attackDamage = 6700;
u.attackRate = 1000;
u.range = 1;
u.armor = 15;
u.resistance = 10;
u.movementRate = 1250;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_orc_rogue";
u.ability.name = "Quickstep";
u.ability.firstCastMs = 1500;
u.ability.cooldownMs = 6500;
u.ability.castMs = 200;
u.ability.recoveryMs = 150;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 3;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemyAdjacent;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Dash;
e.durationMs = 0;
e.magnitude = {0,0,0};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_human_warrior";
u.name = "Cass Vale";
u.displayName = "Cass";
u.race = "human";
u.unitClass = "warrior";
u.cost = 2;
u.roleTags.push_back("melee");
u.health = 98000;
u.attackDamage = 7200;
u.attackRate = 800;
u.range = 1;
u.armor = 25;
u.resistance = 15;
u.movementRate = 1050;
u.attackWindupMs = 350;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_human_warrior";
u.ability.name = "Firm Strike";
u.ability.firstCastMs = 3000;
u.ability.cooldownMs = 7500;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 1;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Physical;
e.durationMs = 0;
e.magnitude = {18000,32400,58300};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_elf_mage";
u.name = "Neris Starbloom";
u.displayName = "Neris";
u.race = "elf";
u.unitClass = "mage";
u.cost = 3;
u.roleTags.push_back("control");
u.health = 69000;
u.attackDamage = 4800;
u.attackRate = 750;
u.range = 4;
u.armor = 8;
u.resistance = 30;
u.movementRate = 1050;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_elf_mage";
u.ability.name = "Starbind";
u.ability.firstCastMs = 3500;
u.ability.cooldownMs = 9500;
u.ability.castMs = 400;
u.ability.recoveryMs = 300;
u.ability.travelMs = 200;
u.ability.radius = 0;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Magic;
e.durationMs = 0;
e.magnitude = {6000,10800,19440};
u.ability.effects.push_back(e); }
{ wc::AbilityEffect e;
e.effect = wc::Effect::Stun;
e.durationMs = 1250;
e.magnitude = {0,0,0};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_dwarf_priest";
u.name = "Orla Hearthglow";
u.displayName = "Orla";
u.race = "dwarf";
u.unitClass = "priest";
u.cost = 2;
u.roleTags.push_back("healer");
u.health = 82000;
u.attackDamage = 3600;
u.attackRate = 700;
u.range = 2;
u.armor = 20;
u.resistance = 25;
u.movementRate = 950;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_dwarf_priest";
u.ability.name = "Hearth Glow";
u.ability.firstCastMs = 3000;
u.ability.cooldownMs = 8000;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 1;
u.ability.range = 1;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::AdjacentAllies;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Heal;
e.durationMs = 0;
e.magnitude = {12500,22500,40500};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_orc_guardian";
u.name = "Tala Ironroot";
u.displayName = "Tala";
u.race = "orc";
u.unitClass = "guardian";
u.cost = 2;
u.roleTags.push_back("tank");
u.health = 112000;
u.attackDamage = 4500;
u.attackRate = 650;
u.range = 1;
u.armor = 30;
u.resistance = 20;
u.movementRate = 900;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_orc_guardian";
u.ability.name = "Shared Guard";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 9500;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 1;
u.ability.range = 1;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::AdjacentAllies;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Shield;
e.durationMs = 3000;
e.magnitude = {14000,25200,45400};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_halfling_warrior";
u.name = "Pippa Oakstride";
u.displayName = "Pippa";
u.race = "halfling";
u.unitClass = "warrior";
u.cost = 1;
u.roleTags.push_back("melee");
u.health = 76000;
u.attackDamage = 5400;
u.attackRate = 950;
u.range = 1;
u.armor = 20;
u.resistance = 10;
u.movementRate = 1200;
u.attackWindupMs = 350;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_halfling_warrior";
u.ability.name = "Stout Heart";
u.ability.firstCastMs = 2000;
u.ability.cooldownMs = 7500;
u.ability.castMs = 250;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 0;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::Self;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Shield;
e.durationMs = 2500;
e.magnitude = {15000,27000,48600};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_halfling_ranger";
u.name = "Finn Thistlearrow";
u.displayName = "Finn";
u.race = "halfling";
u.unitClass = "ranger";
u.cost = 1;
u.roleTags.push_back("ranged");
u.health = 59000;
u.attackDamage = 4900;
u.attackRate = 1000;
u.range = 4;
u.armor = 8;
u.resistance = 10;
u.movementRate = 1250;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_halfling_ranger";
u.ability.name = "Dulling Shot";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 8000;
u.ability.castMs = 300;
u.ability.recoveryMs = 300;
u.ability.travelMs = 150;
u.ability.radius = 0;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::HighestAttackRateEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::StatModifier;
e.durationMs = 3000;
e.magnitude = {-2000,-2500,-3000};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_halfling_rogue";
u.name = "Nella Quickpocket";
u.displayName = "Nella";
u.race = "halfling";
u.unitClass = "rogue";
u.cost = 2;
u.roleTags.push_back("control");
u.health = 66000;
u.attackDamage = 5800;
u.attackRate = 1100;
u.range = 1;
u.armor = 12;
u.resistance = 12;
u.movementRate = 1300;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_halfling_rogue";
u.ability.name = "Quick Feint";
u.ability.firstCastMs = 2000;
u.ability.cooldownMs = 7500;
u.ability.castMs = 200;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 1;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Stun;
e.durationMs = 1000;
e.magnitude = {0,0,0};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_halfling_mage";
u.name = "Milo Mistwhistle";
u.displayName = "Milo";
u.race = "halfling";
u.unitClass = "mage";
u.cost = 2;
u.roleTags.push_back("caster");
u.health = 57000;
u.attackDamage = 4200;
u.attackRate = 800;
u.range = 3;
u.armor = 8;
u.resistance = 20;
u.movementRate = 1150;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_halfling_mage";
u.ability.name = "Mist Pop";
u.ability.firstCastMs = 3000;
u.ability.cooldownMs = 7000;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 200;
u.ability.radius = 1;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemyArea;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Magic;
e.durationMs = 0;
e.magnitude = {13500,24300,43700};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_dragonkin_guardian";
u.name = "Sora Dawnscale";
u.displayName = "Sora";
u.race = "dragonkin";
u.unitClass = "guardian";
u.cost = 3;
u.roleTags.push_back("tank");
u.health = 118000;
u.attackDamage = 4800;
u.attackRate = 650;
u.range = 1;
u.armor = 30;
u.resistance = 30;
u.movementRate = 950;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_dragonkin_guardian";
u.ability.name = "Beacon Shield";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 9000;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 0;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::Self;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Shield;
e.durationMs = 3000;
e.magnitude = {24000,43200,77800};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_dragonkin_ranger";
u.name = "Varek Prismshot";
u.displayName = "Varek";
u.race = "dragonkin";
u.unitClass = "ranger";
u.cost = 2;
u.roleTags.push_back("ranged");
u.health = 72000;
u.attackDamage = 5600;
u.attackRate = 850;
u.range = 4;
u.armor = 12;
u.resistance = 25;
u.movementRate = 1050;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_dragonkin_ranger";
u.ability.name = "Prism Shot";
u.ability.firstCastMs = 3000;
u.ability.cooldownMs = 7500;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 150;
u.ability.radius = 0;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Magic;
e.durationMs = 0;
e.magnitude = {16000,28800,51800};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_dragonkin_rogue";
u.name = "Iri Cinderstep";
u.displayName = "Iri";
u.race = "dragonkin";
u.unitClass = "rogue";
u.cost = 3;
u.roleTags.push_back("control");
u.health = 73000;
u.attackDamage = 6500;
u.attackRate = 1050;
u.range = 1;
u.armor = 15;
u.resistance = 20;
u.movementRate = 1250;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_dragonkin_rogue";
u.ability.name = "Prism Cut";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 8000;
u.ability.castMs = 250;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 1;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::True;
e.durationMs = 0;
e.magnitude = {10000,18000,32400};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_u_dragonkin_priest";
u.name = "Oren Skyward";
u.displayName = "Oren";
u.race = "dragonkin";
u.unitClass = "priest";
u.cost = 2;
u.roleTags.push_back("support");
u.health = 80000;
u.attackDamage = 3800;
u.attackRate = 750;
u.range = 3;
u.armor = 15;
u.resistance = 30;
u.movementRate = 1000;
u.attackWindupMs = 300;
u.projectileTravelMs = 150;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_dragonkin_priest";
u.ability.name = "Sky Ward";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 8000;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 8;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::LowestHealthAlly;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Shield;
e.durationMs = 3000;
e.magnitude = {19000,34200,61600};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.units.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_n_sprout";
u.displayName = "Sprout";
u.name = u.displayName;
u.health = 22000;
u.attackDamage = 1800;
u.attackRate = 700;
u.range = 1;
u.armor = 5;
u.resistance = 5;
u.movementRate = 1000;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.enabled = false;
c.neutrals.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_n_thorn";
u.displayName = "Thorn";
u.name = u.displayName;
u.health = 26000;
u.attackDamage = 2400;
u.attackRate = 750;
u.range = 3;
u.armor = 5;
u.resistance = 5;
u.movementRate = 900;
u.attackWindupMs = 300;
u.projectileTravelMs = 200;
u.damageType = wc::DamageType::Physical;
u.ability.enabled = false;
c.neutrals.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_n_wisp";
u.displayName = "Wisp";
u.name = u.displayName;
u.health = 32000;
u.attackDamage = 2200;
u.attackRate = 650;
u.range = 3;
u.armor = 0;
u.resistance = 15;
u.movementRate = 1000;
u.attackWindupMs = 300;
u.projectileTravelMs = 200;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_neutral_wisp";
u.ability.name = "Spark";
u.ability.firstCastMs = 3000;
u.ability.cooldownMs = 8000;
u.ability.castMs = 350;
u.ability.recoveryMs = 300;
u.ability.travelMs = 200;
u.ability.radius = 0;
u.ability.range = 3;
u.ability.maxTargets = 1;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemy;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Magic;
e.durationMs = 0;
e.magnitude = {6500,6500,6500};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.neutrals.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_n_stoneback";
u.displayName = "Stoneback";
u.name = u.displayName;
u.health = 70000;
u.attackDamage = 4200;
u.attackRate = 600;
u.range = 1;
u.armor = 25;
u.resistance = 5;
u.movementRate = 750;
u.attackWindupMs = 350;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_neutral_stoneback";
u.ability.name = "Shell";
u.ability.firstCastMs = 2000;
u.ability.cooldownMs = 9000;
u.ability.castMs = 350;
u.ability.recoveryMs = 350;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 0;
u.ability.maxTargets = 1;
u.ability.maxDash = 0;
u.ability.allowSelf = true;
u.ability.selector = wc::Selector::Self;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Shield;
e.durationMs = 2500;
e.magnitude = {18000,18000,18000};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.neutrals.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_n_prowler";
u.displayName = "Prowler";
u.name = u.displayName;
u.health = 48000;
u.attackDamage = 3400;
u.attackRate = 1000;
u.range = 1;
u.armor = 10;
u.resistance = 5;
u.movementRate = 1200;
u.attackWindupMs = 250;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_neutral_prowler";
u.ability.name = "Bound";
u.ability.firstCastMs = 2500;
u.ability.cooldownMs = 10000;
u.ability.castMs = 350;
u.ability.recoveryMs = 350;
u.ability.travelMs = 0;
u.ability.radius = 0;
u.ability.range = 8;
u.ability.maxTargets = 1;
u.ability.maxDash = 4;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::FarthestEnemyAdjacent;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Dash;
e.durationMs = 0;
e.magnitude = {0,0,0};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.neutrals.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_n_sentinel";
u.displayName = "Sentinel";
u.name = u.displayName;
u.health = 85000;
u.attackDamage = 4600;
u.attackRate = 650;
u.range = 1;
u.armor = 20;
u.resistance = 15;
u.movementRate = 800;
u.attackWindupMs = 350;
u.projectileTravelMs = 0;
u.damageType = wc::DamageType::Physical;
u.ability.id = "wc_a_neutral_sentinel";
u.ability.name = "Bell shock";
u.ability.firstCastMs = 3500;
u.ability.cooldownMs = 10000;
u.ability.castMs = 450;
u.ability.recoveryMs = 350;
u.ability.travelMs = 0;
u.ability.radius = 1;
u.ability.range = 1;
u.ability.maxTargets = 8;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::AdjacentEnemies;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Stun;
e.durationMs = 750;
e.magnitude = {0,0,0};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.neutrals.push_back(u); }
{ wc::UnitDef u;
u.id = "wc_n_warden";
u.displayName = "Warden";
u.name = u.displayName;
u.health = 140000;
u.attackDamage = 6000;
u.attackRate = 650;
u.range = 3;
u.armor = 20;
u.resistance = 25;
u.movementRate = 800;
u.attackWindupMs = 350;
u.projectileTravelMs = 250;
u.damageType = wc::DamageType::Magic;
u.ability.id = "wc_a_neutral_warden";
u.ability.name = "Beacon burst";
u.ability.firstCastMs = 4000;
u.ability.cooldownMs = 9000;
u.ability.castMs = 600;
u.ability.recoveryMs = 400;
u.ability.travelMs = 250;
u.ability.radius = 1;
u.ability.range = 4;
u.ability.maxTargets = 12;
u.ability.maxDash = 0;
u.ability.allowSelf = false;
u.ability.selector = wc::Selector::CurrentEnemyArea;
{ wc::AbilityEffect e;
e.effect = wc::Effect::Damage;
e.damageType = wc::DamageType::Magic;
e.durationMs = 0;
e.magnitude = {13000,13000,13000};
u.ability.effects.push_back(e); }
u.ability.effect = u.ability.effects[0].effect; u.ability.damageType = u.ability.effects[0].damageType; u.ability.durationMs = u.ability.effects[0].durationMs; u.ability.magnitude = u.ability.effects[0].magnitude;
c.neutrals.push_back(u); }
{ wc::NeutralWave w;
w.id = "wc_wave_01";
w.name = "Garden stirrings";
w.round = 1;
w.hpScaleBp = 10000;
w.damageScaleBp = 10000;
w.slots.push_back({0, {3,3}});
w.slots.push_back({0, {4,3}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_02";
w.name = "Thorn watch";
w.round = 2;
w.hpScaleBp = 10000;
w.damageScaleBp = 10000;
w.slots.push_back({0, {3,3}});
w.slots.push_back({1, {4,1}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_03";
w.name = "Lantern sparks";
w.round = 3;
w.hpScaleBp = 10000;
w.damageScaleBp = 10000;
w.slots.push_back({0, {2,3}});
w.slots.push_back({0, {5,3}});
w.slots.push_back({2, {3,1}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_05";
w.name = "Stone shell";
w.round = 5;
w.hpScaleBp = 12000;
w.damageScaleBp = 15000;
w.slots.push_back({3, {3,3}});
w.slots.push_back({1, {2,1}});
w.slots.push_back({1, {5,1}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_10";
w.name = "Prowler path";
w.round = 10;
w.hpScaleBp = 15600;
w.damageScaleBp = 30000;
w.slots.push_back({3, {3,3}});
w.slots.push_back({4, {1,2}});
w.slots.push_back({4, {6,2}});
w.slots.push_back({2, {3,0}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_15";
w.name = "Bell ward";
w.round = 15;
w.hpScaleBp = 20000;
w.damageScaleBp = 45000;
w.slots.push_back({5, {3,3}});
w.slots.push_back({3, {4,3}});
w.slots.push_back({1, {1,1}});
w.slots.push_back({1, {6,1}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_20";
w.name = "Broken beacon";
w.round = 20;
w.hpScaleBp = 22500;
w.damageScaleBp = 50700;
w.slots.push_back({6, {3,1}});
w.slots.push_back({3, {2,3}});
w.slots.push_back({3, {5,3}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_25";
w.name = "Garden siege";
w.round = 25;
w.hpScaleBp = 27000;
w.damageScaleBp = 45000;
w.slots.push_back({5, {3,3}});
w.slots.push_back({3, {4,3}});
w.slots.push_back({4, {1,2}});
w.slots.push_back({4, {6,2}});
w.slots.push_back({2, {2,0}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_30";
w.name = "Twin ward";
w.round = 30;
w.hpScaleBp = 34000;
w.damageScaleBp = 65000;
w.slots.push_back({5, {2,3}});
w.slots.push_back({5, {5,3}});
w.slots.push_back({1, {1,1}});
w.slots.push_back({1, {6,1}});
w.slots.push_back({2, {3,0}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_35";
w.name = "Beacon breach";
w.round = 35;
w.hpScaleBp = 26000;
w.damageScaleBp = 30000;
w.slots.push_back({6, {3,1}});
w.slots.push_back({5, {2,3}});
w.slots.push_back({3, {5,3}});
w.slots.push_back({4, {1,2}});
w.slots.push_back({4, {6,2}});
c.waves.push_back(w); }
{ wc::NeutralWave w;
w.id = "wc_wave_40";
w.name = "Final ward";
w.round = 40;
w.hpScaleBp = 30000;
w.damageScaleBp = 34000;
w.slots.push_back({6, {3,0}});
w.slots.push_back({5, {2,3}});
w.slots.push_back({5, {5,3}});
w.slots.push_back({4, {1,2}});
w.slots.push_back({4, {6,2}});
w.slots.push_back({2, {4,1}});
c.waves.push_back(w); }
c.traits.push_back({"human","max_health_bonus_bp",2,1000,4,2000});
c.traits.push_back({"elf","attack_rate_bonus_bp",2,1000,4,2000});
c.traits.push_back({"dwarf","physical_armor_flat",2,10,4,20});
c.traits.push_back({"orc","all_damage_bonus_bp",2,1000,4,2000});
c.traits.push_back({"halfling","movement_bonus_bp",2,1000,4,2000});
c.traits.push_back({"dragonkin","magic_resistance_flat",2,15,4,30});
c.traits.push_back({"guardian","physical_armor_flat",2,15,4,30});
c.traits.push_back({"warrior","basic_damage_bonus_bp",2,1500,4,3000});
c.traits.push_back({"ranger","basic_damage_bonus_bp",2,1500,4,3000});
c.traits.push_back({"rogue","attack_rate_bonus_bp",2,1500,4,3000});
c.traits.push_back({"mage","ability_damage_bonus_bp",2,2000,4,4000});
c.traits.push_back({"priest","support_power_bonus_bp",2,1500,4,3000});
{ wc::BotDef b;
b.id = "rowanfield_bot";
b.label = "Rowanfield Bot";
b.decisionIntervalMs = 700;
b.observationMs = 1500;
b.maxCommands = 40;
b.maxRerolls = 4;
b.noiseBp = 500;
b.frontline = 1.3;
b.damage = 1.1;
b.support = 1.0;
b.upgrade = 1.0;
b.synergy = 1.0;
b.level = 1.0;
b.save = 1.0;
c.bots.push_back(b); }
{ wc::BotDef b;
b.id = "starwatch_bot";
b.label = "Starwatch Bot";
b.decisionIntervalMs = 700;
b.observationMs = 1500;
b.maxCommands = 40;
b.maxRerolls = 4;
b.noiseBp = 500;
b.frontline = 1.0;
b.damage = 1.3;
b.support = 0.7;
b.upgrade = 1.0;
b.synergy = 1.2;
b.level = 1.0;
b.save = 0.8;
c.bots.push_back(b); }
{ wc::BotDef b;
b.id = "hearthkeeper_bot";
b.label = "Hearthkeeper Bot";
b.decisionIntervalMs = 700;
b.observationMs = 1500;
b.maxCommands = 40;
b.maxRerolls = 4;
b.noiseBp = 500;
b.frontline = 1.3;
b.damage = 0.9;
b.support = 1.3;
b.upgrade = 1.0;
b.synergy = 1.1;
b.level = 0.9;
b.save = 1.0;
c.bots.push_back(b); }
{ wc::BotDef b;
b.id = "sunstride_bot";
b.label = "Sunstride Bot";
b.decisionIntervalMs = 700;
b.observationMs = 1500;
b.maxCommands = 40;
b.maxRerolls = 4;
b.noiseBp = 500;
b.frontline = 1.2;
b.damage = 1.3;
b.support = 0.7;
b.upgrade = 1.0;
b.synergy = 0.8;
b.level = 0.9;
b.save = 0.5;
c.bots.push_back(b); }
{ wc::BotDef b;
b.id = "gemseeker_bot";
b.label = "Gemseeker Bot";
b.decisionIntervalMs = 700;
b.observationMs = 1500;
b.maxCommands = 40;
b.maxRerolls = 4;
b.noiseBp = 500;
b.frontline = 1.0;
b.damage = 1.0;
b.support = 0.9;
b.upgrade = 1.5;
b.synergy = 1.0;
b.level = 0.7;
b.save = 0.9;
c.bots.push_back(b); }
{ wc::BotDef b;
b.id = "highbanner_bot";
b.label = "Highbanner Bot";
b.decisionIntervalMs = 700;
b.observationMs = 1500;
b.maxCommands = 40;
b.maxRerolls = 4;
b.noiseBp = 500;
b.frontline = 1.1;
b.damage = 1.0;
b.support = 0.9;
b.upgrade = 0.8;
b.synergy = 1.0;
b.level = 1.5;
b.save = 1.1;
c.bots.push_back(b); }
{ wc::BotDef b;
b.id = "wayfinder_bot";
b.label = "Wayfinder Bot";
b.decisionIntervalMs = 700;
b.observationMs = 1500;
b.maxCommands = 40;
b.maxRerolls = 4;
b.noiseBp = 500;
b.frontline = 1.2;
b.damage = 1.1;
b.support = 1.0;
b.upgrade = 1.2;
b.synergy = 1.1;
b.level = 1.1;
b.save = 1.0;
c.bots.push_back(b); }
return c; }
