import hashlib,json
from pathlib import Path
root=Path.cwd();base=root/'reports/WC-U440/20260906T141653Z-orcs'
entries=[('Rok','wc_u_orc_warrior','rok-candidate02/workbench-review'),('Zura','wc_u_orc_mage','zura-candidate02/workbench-fitted'),('Kesh','wc_u_orc_rogue','kesh-contact03/workbench-review')]
records=[]
for name,uid,relative in entries:
    out=base/relative;manifest_path=root/f'exports/heroes/{uid}/export_manifest.json';m=json.loads(manifest_path.read_text());v=json.loads((out/'published-verification.json').read_text());motion=json.loads((out/'motion-invariants.json').read_text());media=json.loads((out/'normal-speed-evidence.json').read_text());ref=json.loads((out/'refinement.json').read_text())
    assert not motion['errors'] and v['status']=='PUBLISHED_SOURCE_EXPORT_AND_MOTION_CHECKS_PASS'
    assert hashlib.sha256(manifest_path.read_bytes()).hexdigest()==v['manifest_sha256']
    records.append({'name':name,'id':uid,'source_revision':m['source_revision'],'geometry_revision':m['geometry_source_revision'],'animation_revision':m['animation_revision'],'source_path':f'art-source/heroes/{uid}/{uid}.blend','source_sha256':m['source_sha256'],'export_folder':f'exports/heroes/{uid}','manifest_sha256':v['manifest_sha256'],'triangles':[m['triangles']]+[lod['triangles'] for lod in m['lods']],'export_files_verified':v['export_files_verified'],'review_directory':out.relative_to(root).as_posix(),'all_authored_frames_evaluated':sum(c['frames_evaluated'] for c in motion['clips']),'actual_60fps_movies':len(media['clips']),'movie_frames_verified':sum(c['video_samples'] for c in media['clips']),'animation_changes':ref.get('animation_changes',[]),'minimum_all_vertex_z_m':min(c['minimum_all_vertex_z_m'] for c in motion['clips']),'Unreal_reimport_verified':False,'continuous_visual_acceptance':False,'final_art_accepted':False})
payload={'status':'SOURCE_AND_MEASURED_EXPORT_HANDOFF_UNREAL_REVIEW_PENDING','blender_version':'5.1.1','entries':records,'actual_60fps_movies':sum(x['actual_60fps_movies'] for x in records),'authored_frames_and_video_samples':sum(x['movie_frames_verified'] for x in records),'retained_failures':['Rok candidate01 circular collar did not drape adequately','Zura candidate01 collar floated above shoulders','Zura candidate02 first portrait and Victory review cropped the staff; framed outputs retained separately','Kesh candidate02 Move all-frame geometry reached -0.0042306688m; candidate03 adds measured support correction','Partial Rok Cycles motion job stopped deliberately for full-frame Workbench path; files/log/exit retained'],'checks_not_run':['Unreal reimport and cold asset verification of revision7','Continuous in-engine all21 clip review','Skill visual and sound alignment','Crowded gameplay camera and LOD review','Packaged runtime and performance of these source revisions'],'metadata_note':'Generic published verifier modified_clips reads the older hand-contact schema and reports empty for Kesh; animation_changes and final export manifest correctly identify Move as changed.'}
(base/'orc-source-handoff.json').write_text(json.dumps(payload,indent=2)+'\n')
print(json.dumps(payload,indent=2))
