"""Generate the per-hero art briefs and image prompts from the catalog and production/hero-art/hero_art.json."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "data/vnext/catalog.json"
ART = ROOT / "production/hero-art/hero_art.json"
OUTPUT = ROOT / "production/hero-art/BRIEFS.md"
# r001 was the rejected toy-like standard (version 1); version 2 images go in r002.
REFERENCE = "art-source/asset-studio/{id}/inputs/references/four_view_r002"
VIEWS = (
    ("main", "FRONT VIEW. The character faces the viewer directly."),
    ("left", "LEFT SIDE VIEW. The camera looks at the character's own left side; the character faces the "
             "left edge of the image, in exact profile."),
    ("back", "BACK VIEW. The camera is directly behind; the character faces away from the viewer."),
    ("right", "RIGHT SIDE VIEW. The camera looks at the character's own right side; the character faces the "
              "right edge of the image, in exact profile."),
)
STYLE = ("Stylized hand-painted fantasy game character for an auto-battler: a grounded fantasy-world hero, not a "
         "toy, not chibi, not a cartoon mascot and not photorealistic. Bold readable silhouette with slightly "
         "exaggerated shoulders, hands and weapon. Believable materials painted with broad brushwork: worn metal "
         "with edge highlights and a few dents, stitched leather, heavy cloth with broad folds. Medium-sized "
         "details only (plate edges, rivets, straps, trim); no micro detail, no noisy texture, no text. Rich "
         "colours with clear light-and-dark contrast. Full body, neutral A-pose with arms about 35 degrees from "
         "the body and legs slightly apart, serious expression looking straight ahead. Straight-on camera at chest "
         "height with minimal perspective, even soft light, plain flat light-grey background #E6E6E6, no ground "
         "shadow, no scenery, no effects. The whole character is inside the frame with margin on every side.")


def design(hero, art):
    colours = ", ".join(f"{name} {code}" for name, code in art["colors"])
    parts = [f"Design: {hero['name']}, a {hero['race']} {hero['unit_class']}. {hero['dossier']['form']}",
             f"About {art['heads']} heads tall; {art['build']}.",
             f"Dominant colours: {colours}; neutral leather, metal and skin tones are allowed beside them.",
             "Features: " + "; ".join(art["features"]) + ".",
             f"Right hand: {art['right_hand']}. Left hand: {art['left_hand']}."]
    if art.get("extra"):
        parts.append("Also: " + art["extra"] + ".")
    return " ".join(parts)


def build():
    heroes = json.loads(CATALOG.read_text(encoding="utf-8"))["heroes"]
    art = json.loads(ART.read_text(encoding="utf-8"))["heroes"]
    missing = [hero["id"] for hero in heroes if hero["id"] not in art]
    if missing or len(art) != len(heroes):
        raise SystemExit(f"Art descriptions must match the catalogue exactly; missing {missing}")
    lines = ["# Hero art briefs", "",
             "Generated by `tools/vnext/build_hero_art_briefs.py` from `data/vnext/catalog.json` and "
             "`production/hero-art/hero_art.json`. Do not edit by hand.", "",
             "Follow [the visual standard](VISUAL_STANDARD.md). Save every image exactly at the path shown.", ""]
    for order, hero in enumerate(heroes, 1):
        entry = art[hero["id"]]
        folder = REFERENCE.format(id=hero["id"])
        text = design(hero, entry)
        lines += [f"## {order:02d}. {hero['name']} — `{hero['id']}`", "",
                  f"{hero['race'].title()} {hero['unit_class'].title()} · cost {hero['cost']} · "
                  f"{'in the game' if hero['enabled'] else 'planned'}", "",
                  f"**Folder:** `{folder}/`", "", "| Colour | Hex |", "|---|---|"]
        lines += [f"| {name} | `{code}` |" for name, code in entry["colors"]]
        lines += ["", "**Design description (identical for every view):**", "", "> " + text, ""]
        for view, camera in VIEWS:
            lines += [f"**`{view}.png`** — prompt:", "", "```text", f"{STYLE} {text} {camera}", "```", ""]
        if entry["accessories"]:
            lines += ["**Accessories** (same style, one item per image, centred, same background):", ""]
            for name, description in entry["accessories"]:
                lines += [f"- `accessories/{name}.png` — {description}, in {hero['name']}'s three colours."]
            lines.append("")
        else:
            lines += ["**Accessories:** none.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = build().encode("utf-8")
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_bytes() != content:
            raise SystemExit("Stale hero art briefs")
        print("Hero art briefs match their sources")
        return
    OUTPUT.write_bytes(content)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
