"""Write final three-hero facial handoff after the sampled sheets have been inspected."""
import hashlib,json
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path('C:/Users/iputu/Documents/Wonder Chess');OUT=Path(__file__).parent
ROWS=[('Neris','wc_u_elf_mage',5,'neris-before-v2'),('Orla','wc_u_dwarf_priest',4,'orla-before'),('Tala','wc_u_orc_guardian',4,'tala-before')]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
heroes=[]
for name,uid,revision,before_dir in ROWS:
    key=name.lower();candidate=OUT/f'{key}-candidate{revision}';verified=OUT/f'{key}-verified{revision}';source=ROOT/f'art-source/heroes/{uid}/{uid}.blend';exports=ROOT/f'exports/heroes/{uid}';m=json.loads((exports/'export_manifest.json').read_text());old=json.loads((candidate/'before-export-manifest.json').read_text());checks=json.loads((verified/'published-verification.json').read_text());detail=json.loads((candidate/'candidate-result.json').read_text());encoded=json.loads((verified/'normal-speed-evidence.json').read_text())
    assert m['source_revision']==revision and sha(source)==m['source_sha256']==checks['source_sha256'];assert sha(exports/'export_manifest.json')==checks['manifest_sha256'];assert all(sha(exports/f)==digest for f,digest in m['files'].items());unchanged=[f for f in m['files'] if old['files'].get(f)==m['files'][f]];assert all(f'AN_{uid}_{clip}.fbx' in unchanged for clip in m['clips']);assert len(encoded['clips'])==7
    heroes.append({'name':name,'unit_id':uid,'source':str(source),'source_sha256':sha(source),'manifest':str(exports/'export_manifest.json'),'manifest_sha256':sha(exports/'export_manifest.json'),'source_revision':revision,'geometry_revision':m['geometry_source_revision'],'animation_revision':m['animation_revision'],'triangles':[x['triangles'] for x in checks['mesh_fbx_readbacks']],'preserved_invariants':detail['preserved_invariants'],'preserved_geometry_signature':detail['preserved_geometry'],'unchanged_export_files':unchanged,'before_views':str(OUT/before_dir),'after_views':str(candidate),'fresh_verification':str(verified/'published-verification.json'),'sampled_motion_evidence':str(verified/'normal-speed-evidence.json'),'source_clip_contact_sheets_inspected':list(m['clips']),'continuous_playback_review':False,'Unreal_reimport_verified_in_this_lane':False,'final_art_accepted':False})
report={'timestamp_utc':datetime.now(timezone.utc).isoformat(),'status':'THREE_FACIAL_SOURCE_REVISIONS_EXPORTED_AND_SAMPLED_REVIEWED','scope':'Only existing eye/iris/pupil/lid/brow surfaces replaced to fit their actual head meshes. Head shell, nose, lips, ears, tusks, hair, braids, headpieces, costume, equipment, palettes, skeleton and all action curves retained.','heroes':heroes,'file_hash_checks':42,'independent_mesh_fbx_readbacks':9,'source_clip_numeric_checks':21,'source_clip_sampled_reviews':21,'continuous_playback_review':False,'final_art_accepted':False,'retained_failure':'Initial read-only Neris inspection assumed a dimensions_m field missing from the component helper. The failed run is retained as neris-before.log; explicit bounds subtraction repaired the helper for fresh neris-before-v2. No source changed in that attempt.','open_reviews':['Actual Unreal material, portrait and LOD transition inspection','Continuous seven-clip playback per hero at gallery/game camera and both orientations','Existing fitted-cloth, anatomy and hand/prop artistic acceptance','Frame times on named hardware and crowded compositions']}
assert not (OUT/'three-face-source-handoff.json').exists();(OUT/'three-face-source-handoff.json').write_text(json.dumps(report,indent=2)+'\n')
lines=['# Neris, Orla and Tala facial source handoff','','The three sources are frozen for Unreal integration. Fresh close front and three-quarter inspection showed separate projecting eye and brow blocks. Each revised asset fits its original eye colors and brow expression to the retained head surface. All other retained vertex coordinates, palette swatches and skin weights match their starting canonical signatures.','','| Hero | Source / geometry / animation | LOD triangles | Before face | After face | Source |','| --- | --- | --- | --- | --- | --- |']
for h in heroes:
    lines.append(f"| {h['name']} | {h['source_revision']} / {h['geometry_revision']} / {h['animation_revision']} | {' / '.join(map(str,h['triangles']))} | [Before](<{Path(h['before_views'])/'face-three-quarter.png'}>) | [After](<{Path(h['after_views'])/'face-three-quarter.png'}>) | [Blend](<{h['source']}>) |")
lines+=['','Verification passed for 42 export hashes, nine independent normalized mesh-FBX readbacks, and 21 saved-source skin/root/scale/action checks. All 21 final source contact sheets were inspected and encoded at 20 Hz / 1x. Their 21 animation FBX hashes remain unchanged. These are sampled source reviews; continuous in-engine playback and finished-art acceptance remain separate.','','Neris retains her low hair knot, broken-circle headpiece and palm focus. Orla retains her silver braids, closed hood and carried octagonal lantern. Tala retains her tusks, tight braids, rounded tower shield and mace. No shared rig/material, canonical data or Unreal binary was changed.','','One read-only helper failure is retained: neris-before.log records an incorrect assumed component-dimensions key. The repaired run derived dimensions from actual bounds and completed in neris-before-v2. All three geometry candidates passed their first executed structural and motion preflight.','','Required remaining integration checks:','']+['- '+x for x in report['open_reviews']]
for h in heroes:lines+=['',f"{h['name']} source SHA-256: `{h['source_sha256']}`",'',f"{h['name']} manifest SHA-256: `{h['manifest_sha256']}`"]
(OUT/'three-face-source-handoff.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':report['status'],'heroes':3,'source_clips':21,'file_hashes':42,'mesh_readbacks':9}))
