// Browser verification of the report viewer only. Uses existing bundled Playwright.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const args = process.argv.slice(2);
const arg = (name, fallback) => {const i=args.indexOf(name);return i<0?fallback:args[i+1];};
const packages = arg('--packages');
const {chromium} = packages ? require(path.join(packages,'playwright')) : require('playwright');
const url = arg('--url','http://127.0.0.1:8874');
const root = path.resolve(__dirname,'../..');
const output = path.join(root,'reports/studio-production-20260930');
fs.mkdirSync(output,{recursive:true});
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];const failures=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  page.on('requestfailed',r=>failures.push(r.url()));
  const response=await page.goto(url,{waitUntil:'networkidle'});
  assert.equal(response.status(),200);
  assert.match(await page.title(),/Wonder Chess/);
  await page.locator('.skill-card').last().waitFor();
  assert.equal(await page.locator('.skill-card').count(),16);
  assert.equal(await page.locator('.report-section').count(),11);
  await page.screenshot({path:path.join(output,'preview-desktop.png'),fullPage:false});
  await page.selectOption('#priority','P0');
  assert.equal(await page.locator('.skill-card').count(),8);
  await page.fill('#search','creature-delivery');
  assert.equal(await page.locator('.skill-card').count(),1);
  await page.locator('.skill-card summary').click();
  assert.match(await page.locator('.skill-card').innerText(),/Human authority/);
  await page.fill('#search','does-not-exist-xyz');
  assert.equal(await page.locator('.skill-card').count(),0);
  assert.match(await page.locator('#skill-grid').innerText(),/No matching/);
  await page.fill('#search','');await page.selectOption('#priority','all');
  await page.selectOption('#collection','existing');
  assert.equal(await page.locator('.skill-card').count(),28);
  await page.locator('.rail nav a[href="#priorities"]').click();
  assert.equal(await page.locator('#priorities').evaluate(e=>e.open),true);
  await page.locator('#expand-all').click();
  assert.equal(await page.locator('.report-section[open]').count(),11);
  await page.locator('#collapse-all').click();
  assert.equal(await page.locator('.report-section[open]').count(),0);
  const download=await page.request.get(new URL('downloads/REPORT.md',url.endsWith('/')?url:url+'/').href);
  assert.equal(download.status(),200);
  assert.match(await download.text(),/SP-08/);
  const data=await page.request.get(new URL('data/skill-catalogue.json',url.endsWith('/')?url:url+'/').href);
  const catalogue=await data.json();assert.equal(catalogue.existing_skills.length,28);
  await page.selectOption('#collection','proposed');
  await page.locator('#recommendation').evaluate(e=>e.open=true);
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>scrollTo(0,0));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  await page.screenshot({path:path.join(output,'preview-mobile.png'),fullPage:false});
  await page.locator('a.button').click();
  assert.equal(await page.locator('#recommendation').evaluate(e=>e.open),true);
  await page.locator('#search').fill('creature-delivery');
  assert.equal(await page.locator('.skill-card').count(),1);
  await page.locator('.skill-card summary').click();
  await page.screenshot({path:path.join(output,'preview-mobile-catalogue.png'),fullPage:false});
  assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);
  const result={status:'PASS_REPORT_BROWSER_ONLY',url,checks:['HTTP 200','nonblank page','16 proposed/28 audited skills','8 priority filter','search/no-match/recovery','card expansion','section navigation/expand/collapse','Markdown/JSON downloads','390px no horizontal overflow','mobile navigation/search'],console_errors:errors,failed_requests:failures,game_acceptance:'NOT_ASSESSED'};
  fs.writeFileSync(path.join(output,url.includes('127.0.0.1')?'browser-verification-local.json':'browser-verification-deployed.json'),JSON.stringify(result,null,2)+'\n');
  console.log(JSON.stringify(result));await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
