import bpy,json,hashlib,sys
from pathlib import Path
from mathutils import Vector
R=Path(__file__).resolve().parents[1];sys.path.insert(0,str(R/'operations'));import check_shoulder as ck
source=R/'ada_bw6_shoulder_r003_combined_review.blend';sha=hashlib.sha256(source.read_bytes()).hexdigest();s=ck.load(source);root=R/'motion/r003';root.mkdir(parents=True,exist_ok=True)
s.frame_start=1;s.frame_end=97;s.frame_step=1;s.render.fps=24;s.render.engine='BLENDER_WORKBENCH';shade=s.display.shading;shade.light='STUDIO';shade.color_type='SINGLE';shade.single_color=(.55,.55,.55);shade.show_shadows=True;shade.show_cavity=True;shade.cavity_type='BOTH';shade.background_type='WORLD';s.world.color=(.09,.09,.09)
s.render.resolution_x=640;s.render.resolution_y=640;s.render.resolution_percentage=100;s.render.image_settings.media_type='IMAGE';s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGB';s.render.film_transparent=False;s.use_nodes=False;s.render.use_sequencer=False;s.view_settings.view_transform='Standard';s.view_settings.look='None'
cameras={'front':bpy.data.objects['BW4_Camera_shoulder']};rear=cameras['front'].copy();rear.data=rear.data.copy();s.collection.objects.link(rear);rear.name='TEMP_BW6_REVIEW_REAR';rear.location=(2,-3,2.2);rear.rotation_euler=(Vector((.24,-.04,1.44))-rear.location).to_track_quat('-Z','Y').to_euler();rear.data.ortho_scale=.52;cameras['rear']=rear
for view,camera in cameras.items():
 folder=root/view;folder.mkdir(exist_ok=True);s.camera=camera;s.render.filepath=str(folder/'frame_');bpy.ops.render.render(animation=True,scene=s.name)
video=bpy.data.scenes.new('BW6_TEMP_DUAL_VIEW_VIDEO');bpy.context.window.scene=video;video.frame_start=1;video.frame_end=97;video.render.resolution_x=1280;video.render.resolution_y=640;video.render.resolution_percentage=100;video.render.fps=24;video.render.image_settings.media_type='VIDEO';video.render.image_settings.file_format='FFMPEG';video.render.ffmpeg.format='MPEG4';video.render.ffmpeg.codec='H264';video.render.ffmpeg.constant_rate_factor='MEDIUM';video.render.ffmpeg.audio_codec='NONE';movie=root/'BW6_SHOULDER_DUAL_VIEW_AUTHORING_NOT_GAME_CLIPS.mp4';video.render.filepath=str(movie);video.view_settings.view_transform='Standard';video.view_settings.look='None';ed=video.sequence_editor_create()
for channel,view,x in [(1,'front',-320),(2,'rear',320)]:
 files=[root/view/f'frame_{f:04}.png' for f in range(1,98)];assert all(p.exists() for p in files);strip=ed.strips.new_image(view,str(files[0]),channel=channel,frame_start=1)
 for p in files[1:]:strip.elements.append(p.name)
 strip.transform.offset_x=x
label=ed.strips.new_effect('Scope',type='TEXT',channel=3,frame_start=1,length=97);label.text='BW6 RIGHT SHOULDER / LOCAL AUTHORING PROOF / NOT GAME CLIPS';label.font_size=22;label.location=(.5,.96);label.color=(1,1,1,1);label.use_shadow=True;video.render.use_sequencer=True;bpy.ops.render.render(animation=True,scene=video.name)
assert hashlib.sha256(source.read_bytes()).hexdigest()==sha
(root/'source_record.json').write_text(json.dumps({'source':str(source),'sha256':sha,'frozen_shoulder_source':str(R/'ada_bw6_shoulder_checkpoint_r003_ART_REVISE.blend'),'frozen_shoulder_sha256':hashlib.sha256((R/'ada_bw6_shoulder_checkpoint_r003_ART_REVISE.blend').read_bytes()).hexdigest(),'movie':str(movie),'movie_sha256':hashlib.sha256(movie.read_bytes()).hexdigest(),'frames':97,'fps':24,'dimensions':[1280,640],'rig_action':bpy.data.objects['BW4_Armor_Independent_Rig'].animation_data.action.name,'cap_support_action':bpy.data.objects['BW6_R_Cap_SecondaryHinge'].animation_data.action.name,'cameras':{n:{'matrix_world':[list(x) for x in c.matrix_world],'ortho_scale':c.data.ortho_scale} for n,c in cameras.items()},'scope':'Actual native Blender renders, every source authoring frame in fixed front/rear shoulder cameras. No real game clip, runtime test, simulation or human approval claim.'},indent=2));print('DUAL_VIEW_MOTION_COMPLETE')
